### ISSUE TITLE
按步骤导出PDF之后没显示markdown的表情

### ISSUE THREAD

**Issue by He1zi** [CarlossShi/markdown-resume#1]
如题，按步骤导出之后，pdf中表情的部分是空白的

**Comment by CarlossShi** [comment]
这个可能是pdf浏览器的问题, 请问是使用什么软件打开的pdf? 试试换使用Adobe Acrobat或者手机打开看看能不能正常显示?

如果要彻底解决问题, 麻烦检查一下:
- `resume-zh.md`文件中是否使用二级标题, 如`## :mortar_board: 教育经历`, 这里使用的标题级数需要和`cv.css`文件中修改了`front-weight`的标题级数对应
- 导出时是否选择了自定主题`Cv`
- `cv.css`中的第[135行](https://github.com/CarlossShi/markdown-resume/blob/c01e288dd4438c628a7fb7190b3335e6a578676d/cv.css#L135)的`font-weight`设置是否在区间[1,599]内

**Comment by He1zi** [comment]
> 这个可能是pdf浏览器的问题, 请问是使用什么软件打开的pdf? 试试换使用Adobe Acrobat或者手机打开看看能不能正常显示?
> 
> 如果要彻底解决问题, 麻烦检查一下:
> 
> * `resume-zh.md`文件中是否使用二级标题, 如`## :mortar_board: 教育经历`, 这里使用的标题级数需要和`cv.css`文件中修改了`front-weight`的标题级数对应
> * 导出时是否选择了自定主题`Cv`
> * `cv.css`中的第[135行](https://github.com/CarlossShi/markdown-resume/blob/c01e288dd4438c628a7fb7190b3335e6a578676d/cv.css#L135)的`font-weight`设置是否在区间[1,599]内

已解决，感谢回复。是打开pdf软件的问题，用的一个叫知云文献翻译的软件打开的，用浏览器或者福昕阅读器就没有问题了。
